### PR TITLE
prototype.py: _registerType(char**, ctypes.POINTER(ctypes.c_char_p)) …

### PR DESCRIPTION
**Pull request by stefoss23**
Some changes in order to make libres to able to run in python3.

### CODE REVIEW

**Comment by JensGM** [comment]
Does this work in python3? The string will not be readable in python3 in any case.

**Comment by stefoss23** [comment]
Yes.

**Comment by stefoss23** [comment]
Most likely, this pr will be closed.

**Comment by andreabrambilla** [comment]
@stefoss23 This looks rather outdated, I'm closing it. Feel free to reopen the PR in case you think this should really go in

**Pull request closed without merging**
