### PR TITLE
Add check that object is initialized before calling bound functions

### PR DESCRIPTION
**Pull request by mortalisk**
Need this so that debugger does not segfault.

### CODE REVIEW

**Comment by eivindjahren** [comment]
Should probably add a small test:
```python
from cwrap import BaseCClass, Prototype, load
import os
import pytest


class LibCPrototype(Prototype):
    lib = load("msvcrt" if os.name == "nt" else None)

    def __init__(self, prototype, bind=False, allow_attribute_error=False):
        super(LibCPrototype, self).__init__(
            LibCPrototype.lib,
            prototype,
            bind=bind,
            allow_attribute_error=allow_attribute_error)


class BadInitialization(BaseCClass):
    TYPE_NAME = "void_libc_none"
    _malloc = LibCPrototype("void* malloc(void*)")
    _abs = LibCPrototype("int abs(int)")
    _free = LibCPrototype("void free(void*)")

    def __init__(self):
        self.abs() # called before initialization, should raise
        c_ptr = self._malloc(4)
        super(LibC, self).__init__(c_ptr)

    def free(self):
        self._free(self.__c_pointer)


def test_that_unitialized_is_raised():
    with pytest.raises(ValueError, match="uninitialized"):
          lib = BadInitialization()

**Comment by mortalisk** [comment]
Added a test based on your example, thanks. Removed some unused lines, and added bind=True, since the check only makes sense for bound methods.

**Comment by valentin-krasontovitsch** [comment]
all tests seem to be failing at the moment :confused:

**Review by eivindjahren — APPROVED** [review]
:bomb:

**Pull request merged**
